# Generated by Django 3.1.7 on 2021-03-15 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam_paper',
            field=models.BooleanField(default=False, help_text='If yes, the result of each attempt by a user will be stored. Necessary for marking.', verbose_name='Show Previous Attempts'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='author',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ReflectionModel', to=settings.AUTH_USER_MODEL, verbose_name='User is automatically assigned'),
        ),
    ]
