# Generated by Django 3.1.7 on 2021-03-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210308_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('How are you?', 'How are u?'), ('Are you good?', 'Are u good?'), ('Django', 'Jango')], max_length=100)),
            ],
        ),
    ]
