# Generated by Django 3.1.7 on 2021-03-15 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210315_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
