# Generated by Django 3.1.7 on 2021-03-09 16:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_questionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('How are you?', 'How are u?'), ('Are you good?', 'Are u good?'), ('Django', 'Jango')], max_length=33),
        ),
    ]
