# Generated by Django 3.1.7 on 2021-03-15 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_reflection_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reflection',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='reflection',
            name='author',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to=settings.AUTH_USER_MODEL, verbose_name='User is automatically assigned'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
