# Generated by Django 3.1.7 on 2021-03-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210315_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reflection',
            options={},
        ),
        migrations.AlterField(
            model_name='reflection',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
