# Generated by Django 3.1.7 on 2021-03-10 14:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210309_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='Answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=200),
        ),
    ]
