# Generated by Django 3.1.7 on 2021-03-16 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0005_auto_20210315_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('author', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailyreflections', to=settings.AUTH_USER_MODEL, verbose_name='User is automatically assigned')),
            ],
        ),
        migrations.CreateModel(
            name='UnitReflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('author', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitreflections', to=settings.AUTH_USER_MODEL, verbose_name='User is automatically assigned')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('author', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeklyreflections', to=settings.AUTH_USER_MODEL, verbose_name='User is automatically assigned')),
            ],
        ),
        migrations.DeleteModel(
            name='Reflection',
        ),
    ]
