# Generated by Django 3.1.7 on 2021-03-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20210310_0845'),
        ('cards', '0006_auto_20210310_0851'),
    ]

    operations = [
    ]
