# Generated by Django 3.1.7 on 2021-03-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_reflection_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='body',
            field=models.TextField(),
        ),
    ]
